### ISSUE TITLE
NullReferenceException when setting the ID3Tag

### ISSUE THREAD

**Issue by gabriel-munteanu** [Corey-M/NAudio.Lame#42] opened 2020-04-16 15:21 UTC
For this line
`var mp3Writer = new LameMP3FileWriter(outputPath, resultTrack.WaveFormat, 128, config.GetID3Tag());`
I get a NullReferenceException. I saw that this happens only when I set the ID3Tag parameter.

From my debugging I found that the exception is thrown here: https://github.com/Corey-M/NAudio.Lame/blob/master/NAudio.Lame/LameMP3FileWriter.cs#L446 because `data` is null.
Why?
I saw that you have some tests around setting the ID3Tag but I don't understand how those pass.

Can I get some help?

**Comment by gabriel-munteanu** [comment] 2020-04-17 13:55
I narrowed down the problem: if you don't set the Genre you will get the exception.
Why?

**Comment by shadowsoulxp** [comment] 2020-05-24 13:47
The issue is on the line that Garbriel mentions,

I imported the whole project into my project to debug from there. it seems that the "data" is null in some cases (I have not figured out why).

The solution for me was to add a `data != null && ` to line 445. The automatic writing of the tag seems to work just fine (I'm only editing title, artist, year, comment and genre of the tag).

**Comment by Corey-M** [comment] 2020-05-25 03:49
My bad.  I assumed that `ID3GetID3v2Tag` would return non-null.  I'll add a null-value check.

**Comment by Corey-M** [comment] 2020-05-25 04:22
After a bit of testing it turns out that lame won't create an ID3v2 tag if the supplied ID3 data fits inside an ID3v1 tag, so it's not just the Genre field not being supplied.  This will be fixed shortly.

**Closed** 2020-05-25 06:03 UTC
