### ISSUE TITLE
type or namespace name 'Lame' does not exist in the namespace 'NAudio', v1.1.0

### ISSUE THREAD

**Issue by catalinr** [Corey-M/NAudio.Lame#36] opened 2020-01-22 04:33 UTC
`using NAudio.Lame`
I'm getting the same error reported in #33 when using v1.1.0 `Date published: Wednesday, December 25, 2019 (12/25/2019)`.
VS 2019 v16.3.10, NAudio.Lame installed with NuGet Package manager. NAudio v1.9.0 was also installed.

**Comment by Corey-M** [comment] 2020-02-25 15:21
Can you reproduce this in a minimal solution and attach it here?  I can't reproduce.

**Comment by antiqtech** [comment] 2020-04-01 23:57
I just created an example project to test out Naudio.lame but I'm getting the same error. 
I installed Naudio and Naudio.Lame. 
I'm attaching the project here
[WavMP3Converter.zip](https://github.com/Corey-M/NAudio.Lame/files/4418152/WavMP3Converter.zip)
![image](https://user-images.githubusercontent.com/44986207/78197280-83e11b00-748d-11ea-98b3-2bb827fdf58b.png)
![image](https://user-images.githubusercontent.com/44986207/78197302-95c2be00-748d-11ea-9132-1c6f3fe1111b.png)

**Comment by antiqtech** [comment] 2020-04-02 00:01
I uninstalled 1.1.0 and installed instead 1.0.9 . I'm not getting the error anymore ://

**Comment by Corey-M** [comment] 2020-04-06 01:38
OK, NAudio.Lame v1.1.1 is up on NuGet.  This links to NAudio v1.10.0, resolving this issue.

**Closed by Corey-M** 2020-04-06 01:38 UTC
